CREATE TABLE sik.kelahiran_bayi_structure (
    no_rkm_medis character varying(15) NOT NULL,
    nm_pasien character varying(40),
    jk character varying(12),
    tmp_lahir character varying(15),
    tgl_lahir date,
    jam time without time zone,
    umur character varying(30),
    tgl_daftar date,
    nm_ibu character varying(40),
    umur_ibu character varying(30),
    nm_ayah character varying(40),
    umur_ayah character varying(30),
    alamat text,
    bb integer,
    pb numeric(5,2),
    proses_lahir character varying(100),
    kelahiran_ke integer,
    keterangan text,
    diagnosa character varying(100),
    penyulit_kehamilan character varying(100),
    ketuban character varying(30),
    lk_perut numeric(5,2),
    lk_kepala numeric(5,2),
    lk_dada numeric(5,2),
    penolong character varying(30),
    no_skl character varying(30),
    gravida integer,
    para integer,
    abortus integer,
    f1 integer,
    u1 integer,
    t1 integer,
    r1 integer,
    w1 integer,
    n1 integer,
    f5 integer,
    u5 integer,
    t5 integer,
    r5 integer,
    w5 integer,
    n5 integer,
    f10 integer,
    u10 integer,
    t10 integer,
    r10 integer,
    w10 integer,
    n10 integer,
    resusitas character varying(100),
    obat text,
    mikasi character varying(100),
    mikonium character varying(100),
    no_rm_ibu character varying(15)
);


COPY sik.kelahiran_bayi_structure (no_rkm_medis, nm_pasien, jk, tmp_lahir, tgl_lahir, jam, umur, tgl_daftar, nm_ibu, umur_ibu, nm_ayah, umur_ayah, alamat, bb, pb, proses_lahir, kelahiran_ke, keterangan, diagnosa, penyulit_kehamilan, ketuban, lk_perut, lk_kepala, lk_dada, penolong, no_skl, gravida, para, abortus, f1, u1, t1, r1, w1, n1, f5, u5, t5, r5, w5, n5, f10, u10, t10, r10, w10, n10, resusitas, obat, mikasi, mikonium, no_rm_ibu) FROM stdin;
\.


ALTER TABLE ONLY sik.kelahiran_bayi_structure
    ADD CONSTRAINT kelahiran_bayi_pkey PRIMARY KEY (no_rkm_medis);
